#!/usr/bin/env python3
"""
This is a more or less simple script for generating a .jl file from
the doxygen output of libsemigroups.

Usage: TODO
"""

import re
import sys
import argparse

from os.path import isfile, exists
from functools import cache
from glob import glob
from accepts import accepts
from textwrap import fill

import bs4
from bs4 import BeautifulSoup

import pdb  # TODO rm

__DOXY_DICT = {}
__ABSTRACT_CLASSES = {}
__DOXY_DIR = None

########################################################################
# Copyright / Headers / Footers
########################################################################


def copyright(thing: str) -> str:
    doc = fill(
        f"This file provides user-facing {thing} functionality with idiomatic Julia interfaces: 1-based indexing, and standard Julia operators.",
        width=80,
    )
    return f"""# Copyright (c) 2026, James W. Swent, J. D. Mitchell
#
# Distributed under the terms of the GPL license version 3.
#
# The full license is in the file LICENSE, distributed with this software.

# This file was at least partially auto-generated by
#
# {" ".join(sys.argv)}

\"\"\"
{to_jl_type(thing.lower())}.jl - High-level Julia API for {thing}

{doc}
\"\"\"

"""


########################################################################
# Internal helpers
########################################################################


def __error(msg: str) -> None:
    sys.stderr.write(f"\033[0;31m{msg}\n\033[0m")


def __bold(msg: str) -> None:
    sys.stderr.write(f"\033[1m{msg}\n\033[0m")


def __parse_args() -> argparse.Namespace:
    global __DOXY_DIR
    parser = argparse.ArgumentParser(
        prog="doxy_to_jl_file.py", usage="%(prog)s [options]"
    )
    parser.add_argument(
        "things",
        nargs="+",
        help="the things (classes, structs, namespaces) to create bindings for",
    )

    parser.add_argument(
        "--doxy-dir",
        nargs=1,
        type=str,
        default="docs/xml",
        help="the path to the xml generated by Doxygen",
    )

    args = parser.parse_args()
    __DOXY_DIR = args.doxy_dir[0]
    __bold(f'Finding doxygen xml output in "{__DOXY_DIR}" . . .')
    return args


def __wrap_text(text: str, width: int = 80) -> str:
    paragraphs = text.split("\n\n")
    wrapped = [fill(p, width=width) for p in paragraphs]
    return "\n\n".join(wrapped)


########################################################################
# Doxygen XML parsing (adapted from generate_pybind11.py)
########################################################################


@cache
@accepts(str)
def doxygen_filename(thing: str) -> str:
    orig = thing
    thing = re.sub("_", "__", thing)
    if thing.endswith("_group"):
        fname = f"{__DOXY_DIR}/group__{thing}.xml"
        if exists(fname) and isfile(fname):
            return fname
    p = re.compile(r"::")
    thing = p.sub("_1_1", thing)
    # Try Doxygen CamelCase encoding first: insert _ before uppercase,
    # lowercase all. This avoids accidentally matching a namespace file
    # when a class was intended (e.g. BMat8 class vs bmat8 namespace).
    thing_doxy = re.sub(r"([A-Z])", lambda m: "_" + m.group(1).lower(), thing)
    for possible in ("class", "struct"):
        fname = f"{__DOXY_DIR}/{possible}{thing_doxy}.xml"
        if exists(fname) and isfile(fname):
            return fname
    # Try exact match for class/struct/namespace
    for possible in ("class", "struct", "namespace"):
        fname = f"{__DOXY_DIR}/{possible}{thing}.xml"
        if exists(fname) and isfile(fname):
            return fname
    # Try CamelCase encoding for namespace
    for possible in ("namespace",):
        fname = f"{__DOXY_DIR}/{possible}{thing_doxy}.xml"
        if exists(fname) and isfile(fname):
            return fname
    # Fall back to group files
    thing = thing.split("_1_1")[-1]
    pattern = re.compile(rf">{thing}<")
    for fname in glob(f"{__DOXY_DIR}/group__*.xml"):
        with open(fname, "r", encoding="utf-8") as file:
            lines = file.read()
        if pattern.search(lines):
            return fname
    __error(f'Can\'t find the doxygen file for "{orig}" IGNORING!!!')
    return ""


@accepts(str, str | None, str | None)
def get_xml(
    thing: str, fn: str | None = None, params_t: str | None = None
) -> dict[str, bs4.element.Tag]:
    if thing not in __DOXY_DICT:
        with open(doxygen_filename(thing), "r", encoding="utf-8") as xml:
            xml = BeautifulSoup(xml, "xml")
            compounddefs = xml.find_all("compounddef")

            for compounddef in compounddefs:
                if "abstract" in compounddef.attrs and compounddef["abstract"] == "yes":
                    __ABSTRACT_CLASSES[thing] = True
            fn_list = xml.find_all("memberdef")
            fn_dict = {}

            for x in fn_list:
                nm = x.find("name").text
                if nm not in fn_dict:
                    fn_dict[nm] = {}
                tparam = x.find("templateparamlist")
                if tparam is not None:
                    tparam = tparam.find_all("param")
                    tparam = [x.find("type").text.strip() for x in tparam]
                param = x.find_all("param")
                param = [x.find("type").text.strip() for x in param]
                if tparam is not None:
                    param = [x for x in param if x not in tparam]
                param = ",".join(param)

                fn_dict[nm][param] = x
            __DOXY_DICT[thing] = fn_dict
    if fn is not None:
        if params_t == "" and len(__DOXY_DICT[thing][fn]) == 1:
            return list(__DOXY_DICT[thing][fn].values())[0]
        if params_t is not None:
            return __DOXY_DICT[thing][fn][params_t]
        return __DOXY_DICT[thing][fn]
    return __DOXY_DICT[thing]


########################################################################
# Query functions (from generate_pybind11.py)
########################################################################


@cache
@accepts(str, str, str)
def is_public(thing: str, fn: str, params_t: str) -> bool:
    if is_namespace(thing):
        return True
    xml = get_xml(thing, fn, params_t)
    prot = xml.get("prot")
    return prot is not None and prot == "public"


# @cache
# @accepts(str, str, str)
# def is_enum(thing: str, fn: str, params_t: str) -> bool:
#     xml = get_xml(thing, fn, params_t)
#     kind = xml.get("kind")
#     return kind is not None and kind == "enum"


@cache
@accepts(str, str, str)
def is_typedef(thing: str, fn: str, params_t: str) -> bool:
    xml = get_xml(thing, fn, params_t)
    kind = xml.get("kind")
    return kind is not None and kind == "typedef"


@cache
@accepts(str)
def class_template_params(thing: str) -> list[str]:
    result = []
    doxy_file = doxygen_filename(thing)
    if is_namespace(thing) or not doxy_file:
        return result
    with open(doxy_file, "r", encoding="utf-8") as xml:
        xml = BeautifulSoup(xml, "xml")
        for x in xml.doxygen.compounddef.children:
            if x.name == "templateparamlist":
                for y in x.find_all("param"):
                    result.append(y.find("type").text)
                    if y.find("declname") is not None:
                        result[-1] += " " + y.find("declname").text
    return result


@cache
@accepts(str)
def is_class_template(thing: str) -> bool:
    return len(class_template_params(thing)) != 0


# @cache
# @accepts(str, str)
# def is_overloaded(thing: str, fn: str) -> bool:
#     return len(get_xml(thing, fn)) > 1


@cache
@accepts(str)
def is_namespace(thing: str) -> bool:
    return "namespace" in doxygen_filename(thing)


@cache
@accepts(str)
def is_free_fn(thing: str) -> bool:
    return doxygen_filename(thing).startswith(f"{__DOXY_DIR}/group__")


# @cache
# @accepts(str, str, str)
# def is_static_mem_fn(thing: str, fn: str, params_t: str) -> bool:
#     if is_namespace(thing) or is_free_fn(thing):
#         return False
#     xml = get_xml(thing, fn, params_t)
#     return xml["static"] == "yes"


@cache
@accepts(str, str, str)
def is_mem_fn(thing: str, fn: str, params_t: str) -> bool:
    return not is_namespace(thing) and not is_free_fn(thing)


# @cache
# @accepts(str)
# def is_abstract_class(thing: str) -> bool:
#     return thing in __ABSTRACT_CLASSES


@cache
@accepts(str, str, str)
def has_documented_throw(thing: str, fn: str, params_t: str) -> bool:
    xml = get_xml(thing, fn, params_t)
    for paramlist in xml.find_all("parameterlist"):
        if paramlist["kind"] == "exception":
            return True
    return False


@cache
@accepts(str, str, str)
def params_dict(thing: str, fn: str, params_t: str) -> dict[str, str]:
    xml = get_xml(thing, fn, params_t)
    result = {}
    for x in xml.find_all("param"):
        type_ = x.find("type").text
        if not type_.startswith("typename"):
            name = x.find("declname")
            if name:
                result[name.text] = type_
    return result


@cache
@accepts(str, str, str)
def return_type(thing: str, fn: str, params_t: str) -> str:
    if is_constructor(thing, fn):
        return thing
    xml = get_xml(thing, fn, params_t)
    return xml.find("type").text


@accepts(str, str, str)
def param_names_str(thing: str, fn: str, params_t: str) -> list[str]:
    return list(params_dict(thing, fn, params_t).keys())


# @accepts(str, str, str)
# def fn_sig(thing: str, fn: str, params_t: str) -> list[str]:
#     params_d = params_dict(thing, fn, params_t)
#     result = []
#     for name, type_ in params_d.items():
#         result.append(f"{type_} {name}")
#     return result


@accepts(str)
def shortname(thing: str) -> str:
    if thing.startswith("libsemigroups::"):
        return thing[len("libsemigroups::") :]
    return thing


# @accepts(str)
# def shortname_(thing: str) -> str:
#     name = shortname(thing)
#     if is_class_template(thing):
#         name += "_"
#     return name


# @cache
# @accepts(str, str, str)
# def is_const_mem_fn(thing: str, fn: str, params_t: str) -> bool:
#     if is_namespace(thing):
#         return False
#     xml = get_xml(thing, fn, params_t)
#     assert "const" in xml.attrs, "const not an attribute!"
#     return xml["const"] == "yes"


@cache
@accepts(str, str, str)
def is_deleted_mem_fn(class_n: str, mem_fn: str, params_t: str) -> bool:
    xml = get_xml(class_n, mem_fn, params_t)
    if xml.find("argsstring") is None:
        return False
    return xml.find("argsstring").text.find("=delete") != -1


@cache
@accepts(str, str)
def is_constructor(class_n: str, mem_fn: str) -> bool:
    return not is_free_fn(class_n) and mem_fn.startswith(class_n.split("::")[-1])


# @cache
# @accepts(str, str)
# def is_operator(_: str, mem_fn: str) -> bool:
#     return mem_fn.startswith("operator") or mem_fn in ("at", "hash_value")


# @cache
# @accepts(str, str)
# def is_iterator(_: str, mem_fn: str) -> bool:
#     # Only use cbegin to avoid duplicate with begin
#     return mem_fn.startswith("cbegin")


@cache
@accepts(str, str, str)
def brief(thing: str, fn: str, params_t: str) -> str:
    xml = get_xml(thing, fn, params_t)
    return xml.find("briefdescription").text.strip()


@cache
@accepts(str, str, str)
def detailed(thing: str, fn: str, params_t: str) -> str:
    xml = get_xml(thing, fn, params_t)
    return xml


########################################################################
# Skip logic
########################################################################


@accepts(str, str, str)
def skip_fn(thing: str, fn: str, params_t: str) -> bool:
    if (
        fn.endswith("_no_checks")
        or "initializer_list" in params_t
        or fn.startswith("cend")
        or fn.startswith("end")
        or fn.startswith("begin")
        or fn.startswith("cbegin")
        or fn.startswith("operator")
        or "&&" in params_t
        or ("*" in params_t and params_t.strip() != "bool(*)()")
        or "*" in return_type(thing, fn, params_t)
        or is_typedef(thing, fn, params_t)
        or brief(thing, fn, params_t).startswith("Deduction guide")
    ):
        return True
    try:
        get_xml(thing, fn, params_t)
    except KeyError:
        return True
    return is_deleted_mem_fn(thing, fn, params_t) or not is_public(thing, fn, params_t)


#########################################################################
# Convert to jl
########################################################################


# TODO rename
@accepts(str)
def to_jl_type(param_type: str) -> str:
    param_type = param_type.replace("libsemigroups::", "")
    param_type = re.sub(r"\bconst\b", "", param_type)
    param_type = re.sub(r"\bconstexpr\b", "", param_type)
    param_type = param_type.replace(r"&", "")
    param_type = re.sub(r"\bsize_t\b", "Int64", param_type)
    param_type = param_type.replace("uint8_t", "Int64")
    param_type = param_type.replace("bool", "Bool")
    param_type = param_type.replace("typename", "")
    param_type = param_type.replace("std::vector", "Vector")
    param_type = param_type.replace("<", "{")
    param_type = param_type.replace(">", "}")
    param_type = param_type.replace(" ", "")
    param_type = param_type.replace("void", "nothing")
    param_type = param_type.replace("uint64_t", "UInt64")
    param_type = param_type.replace("node_type", "Integer")
    param_type = param_type.replace("std::string", "String")

    return param_type


@accepts(str, str, str, bool)
def to_jl_sig(
    thing: str, fn_name: str, param_types: str, include_return_type: bool = False
) -> str:
    if is_mem_fn(thing, fn_name, param_types) and not is_constructor(thing, fn_name):
        params = {"self": f"{thing}"}
    else:
        params = dict()
    params = params | params_dict(thing, fn_name, param_types)
    result = f"{fn_name}("
    result += ",".join(f"{name}::{to_jl_type(type_)}" for name, type_ in params.items())
    result += ")"
    if include_return_type:
        result += f"::{to_jl_type(return_type(thing, fn_name, param_types))}"
    return result


# TODO accepts
def to_jl_ref(thing: str, fn_name: str | None = None, param_types: str | None = None):
    if fn_name is None and param_types is None:
        sig, name = shortname(thing), shortname(thing)
    elif param_types is None:
        sig, name = shortname(fn_name), shortname(fn_name)
    else:
        sig, name = (
            to_jl_sig(thing, fn_name, param_types, include_return_type=False),
            shortname(fn_name),
        )

    return f"[`{name}`](@ref Semigroups.{sig})"


# TODO rename this -> cxx_idioms_to_jl
def to_jl_doc(text: str) -> str:
    text = re.sub(r"\ba\s+const\s+reference\s+to\s+a\b", "a", text)
    text = re.sub(r"\ba\s+reference\s+to\s+a\b", "a", text)
    text = re.sub(r"\ba\s+const\s+reference\b", "", text)
    text = re.sub(r"\ba\s+reference\b", "", text)
    text = re.sub(r"\bconst\s+reference\b", "", text)
    text = re.sub(r"\breference\b", "", text)
    text = re.sub(r"\bvector\b", "`Vector`", text)
    text = re.sub(r"\bunsigned int\b", "integer", text)
    text = re.sub(r"`this`", "`self`", text)
    # text = re.sub(r"\bUNDEFINED\b", "[`UNDEFINED`](@ref)", text)
    return text


def convert_to_jl_doc(xml, context=[], params_dict: dict[str, str] = {}) -> str:
    context.append(xml.name)
    if "kind" in xml.attrs and xml.attrs["kind"] == "enum":
        context.append(xml.attrs["kind"])

    result = ""
    if xml.name == "compounddef":
        try:
            t = next((x for x in xml if x.name == "templateparamlist"))
            xml = [t] + [x for x in xml if x.name != "templateparamlist"]
        except StopIteration:
            pass
    if (
        not isinstance(xml, list)
        and "kind" in xml.attrs
        and xml.attrs["kind"] == "enum"
    ):
        n = next((x for x in xml if x.name == "name"))
        bd = ""
        try:
            bd = next((x for x in xml if x.name == "briefdescription"))
        except StopIteration:
            pass
        xml = [n, bd] + [x for x in xml if x.name not in ("briefdescription", "name")]
    for x in xml:
        if isinstance(x, str):
            x = x.strip()
            result += " " if x != "." and x != "" and not x[0].isupper() else ""
            result += x
        elif "enum" in context and x.name == "name":
            result += x.text.strip()
        elif "enum" in context and x.name == "enumvalue":
            # TODO convert from python to julia
            result += "\n\n.. py:enumerator:: "
            result += convert_to_jl_doc(x, context, params_dict)
        elif x.name == "briefdescription":
            result += (
                __wrap_text(convert_to_jl_doc(x, context, params_dict), width=80)
                + "\n\n"
            )
        elif x.name == "detaileddescription":
            result += "\n" + __wrap_text(
                convert_to_jl_doc(x, context, params_dict), width=80
            )
        elif x.name == "templateparamlist":
            params = []
            for y in x.find_all("param"):
                z = y.type.text
                if y.declname is not None:
                    z += " " + y.declname.text
                params.append(z)
            result += "template <" + ", ".join(params) + ">"
        elif x.name == "computeroutput":
            if len(x.text) != 0:
                result += f" `{x.text}`"
        elif x.name == "formula":
            result += f" ``{x.text.replace('$', '')}``"
        elif x.name == "title":
            result += f"\n\n# {x.text}\n\n"
        elif x.name == "para":
            result += convert_to_jl_doc(x, context, params_dict)
        elif x.name == "simplesect" and x.attrs["kind"] == "par":
            result += convert_to_jl_doc(x, context, params_dict)
        elif x.name == "parameterlist" and x.attrs["kind"] == "exception":
            for y in x.find_all("parameteritem"):
                exception = y.find("parametername").text
                if exception == "LibsemigroupsException":
                    exception = "LibsemigroupsError"
                result += "\n\n"
                if "Throws" not in result:
                    result += "# Throws"
                result += f"\n\n- {exception}: "
                result += convert_to_jl_doc(y.find("parameterdescription"), context)
        elif x.name == "parameterlist" and x.attrs["kind"] == "param":
            result += "\n\n# Arguments\n"
            paramitem = x.find_all("parameteritem")
            for y in paramitem:
                name = y.find("parametername").text
                if name in params_dict:
                    rtype = to_jl_type(params_dict[name])
                else:
                    rtype = "TODO"

                des = "\n\n".join(
                    des.text for des in y.find("parameterdescription").find_all("para")
                )
                result += f"\n - `{name}::{rtype}`: {des}\n"
        elif x.name == "simplesect" and x.attrs["kind"] == "see":
            result += "\n\n# See also\n\n-" + convert_to_jl_doc(x, context, params_dict)
        elif x.name == "ref":
            # TODO remove () from reference text
            text = x.text.replace("()", "")
            result += f" [`{text}`](@ref)"
        elif x.name == "emphasis":
            # TODO convert from python to julia
            result += f" *{x.text}*"
        elif x.name == "bold":
            # TODO convert from python to julia
            result += f"**{x.text}**"
        elif x.name == "compoundname":
            result += x.text[x.text.rfind("::") + 2 :]
        elif x.name == "ulink":
            # TODO convert from python to julia
            result += f"`{x.text} <{x.attrs['url']}>`_"
        elif x.name == "itemizedlist":
            result += "\n" + convert_to_jl_doc(x, context, params_dict)
        elif x.name == "listitem":
            result += "\n* " + convert_to_jl_doc(x, context, params_dict)
        elif x.name == "programlisting":
            # TODO convert from python to julia
            result += "\n\n.. code-block::\n" + convert_to_jl_doc(x)
        elif x.name == "codeline":
            result += "\n" + convert_to_jl_doc(x)
        elif x.name == "highlight":
            result += convert_to_jl_doc(x)
        elif x.name == "sp":
            result += " "

    if len(context) > 0 and context[-1] == "enum":
        context.pop()
    if context.pop() == "itemizedlist":
        result += "\n\n"

    return to_jl_doc(result)


########################################################################
# Orchestrator
########################################################################


@accepts(str, str, str)
def generate_func_doc(thing: str, fn: str, params_t: str) -> str:
    xml = get_xml(thing, fn, params_t)
    result = f"    {to_jl_sig(thing, fn, params_t, include_return_type=True)}\n\n"
    result += convert_to_jl_doc(xml, [], params_dict(thing, fn, params_t))

    result = re.sub(r"\s+,", ",", result)
    result = re.sub(r"\s+\.", ".", result)
    result = re.sub(
        r"# Exceptions\s*\n\nThis function is `noexcept` and is guaranteed never to throw.\s*\n?",
        "",
        result,
    )
    result = re.sub(
        r"# Exceptions\s*\n\nThis function guarantees not to throw.*\n?",
        "",
        result,
    )
    result = re.sub(r"\n{2,}", "\n\n", result)
    return result


@accepts(str, str, str)
def generate_func_decl(thing: str, fn: str, params_t: str) -> str:
    result = to_jl_sig(thing, fn, params_t, include_return_type=True)
    result += " = "
    if has_documented_throw(thing, fn, params_t):
        result += "@wrap_libsemigroups_call "

    result += "LibSemigroups."
    if not is_constructor(thing, fn):
        result += f"{to_jl_type(thing).lower()}_"
    result += f"{to_jl_type(fn)}("

    if is_mem_fn(thing, fn, params_t) and not is_constructor(thing, fn):
        params = ["self"]
    else:
        params = []
    params.extend(param_names_str(thing, fn, params_t))
    result += ", ".join(params) + ")\n"
    return result


@accepts(str, str, str)
def generate_func(thing: str, fn: str, params_t: str) -> str:
    return (
        '"""\n'
        + generate_func_doc(thing, fn, params_t)
        + '\n"""'
        + "\n"
        + generate_func_decl(thing, fn, params_t)
        + "\n"
    )


@accepts(str)
def generate(thing: str) -> str:
    if len(doxygen_filename(thing)) == 0:
        return ""

    result = copyright(thing)
    xml = get_xml(thing)
    for fn, sigs in sorted(xml.items()):
        for sig in sigs.keys():
            if not skip_fn(thing, fn, sig):
                result += generate_func(thing, fn, sig)
    return result


########################################################################
# main
########################################################################


def main():
    if sys.version_info[0] < 3:
        raise Exception("Python 3 is required")
    args = __parse_args()

    for thing in args.things:
        print(generate(thing))


if __name__ == "__main__":
    main()
