#!/usr/bin/env python3
"""
TODO
"""

import re
import sys
import argparse

from os.path import isfile, exists
from functools import cache
from glob import glob
from accepts import accepts

import bs4
from bs4 import BeautifulSoup

__DOXY_DICT = {}
__ABSTRACT_CLASSES = {}

########################################################################
# Copyright / Headers / Footers
########################################################################

__DOXY_DIR = None

########################################################################
# Internal helpers
########################################################################


def __error(msg: str) -> None:
    sys.stderr.write(f"\033[0;31m{msg}\n\033[0m")


def __bold(msg: str) -> None:
    sys.stderr.write(f"\033[1m{msg}\n\033[0m")


def __parse_args() -> argparse.Namespace:
    global __DOXY_DIR
    parser = argparse.ArgumentParser(prog="generate_jlcxx", usage="%(prog)s [options]")
    parser.add_argument(
        "things",
        nargs="+",
        help="the things (classes, structs, namespaces) to create bindings for",
    )

    parser.add_argument(
        "--doxy-dir",
        nargs=1,
        type=str,
        default="docs/xml",
        help="the path to the xml generated by Doxygen",
    )

    args = parser.parse_args()
    __DOXY_DIR = args.doxy_dir[0]
    __bold(f'Finding doxygen xml output in "{__DOXY_DIR}" . . .')
    return args


########################################################################
# Doxygen XML parsing (adapted from generate_pybind11.py)
########################################################################


@cache
@accepts(str)
def doxygen_filename(thing: str) -> str:
    orig = thing
    thing = re.sub("_", "__", thing)
    if thing.endswith("_group"):
        fname = f"{__DOXY_DIR}/group__{thing}.xml"
        if exists(fname) and isfile(fname):
            return fname
    p = re.compile(r"::")
    thing = p.sub("_1_1", thing)
    # Try Doxygen CamelCase encoding first: insert _ before uppercase,
    # lowercase all. This avoids accidentally matching a namespace file
    # when a class was intended (e.g. BMat8 class vs bmat8 namespace).
    thing_doxy = re.sub(r"([A-Z])", lambda m: "_" + m.group(1).lower(), thing)
    for possible in ("class", "struct"):
        fname = f"{__DOXY_DIR}/{possible}{thing_doxy}.xml"
        if exists(fname) and isfile(fname):
            return fname
    # Try exact match for class/struct/namespace
    for possible in ("class", "struct", "namespace"):
        fname = f"{__DOXY_DIR}/{possible}{thing}.xml"
        if exists(fname) and isfile(fname):
            return fname
    # Try CamelCase encoding for namespace
    for possible in ("namespace",):
        fname = f"{__DOXY_DIR}/{possible}{thing_doxy}.xml"
        if exists(fname) and isfile(fname):
            return fname
    # Fall back to group files
    thing = thing.split("_1_1")[-1]
    pattern = re.compile(rf">{thing}<")
    for fname in glob(f"{__DOXY_DIR}/group__*.xml"):
        with open(fname, "r", encoding="utf-8") as file:
            lines = file.read()
        if pattern.search(lines):
            return fname
    __error(f'Can\'t find the doxygen file for "{orig}" IGNORING!!!')
    return ""


@accepts(str, str | None, str | None)
def get_xml(
    thing: str, fn: str | None = None, params_t: str | None = None
) -> dict[str, bs4.element.Tag]:
    if thing not in __DOXY_DICT:
        with open(doxygen_filename(thing), "r", encoding="utf-8") as xml:
            xml = BeautifulSoup(xml, "xml")
            compounddefs = xml.find_all("compounddef")

            for compounddef in compounddefs:
                if "abstract" in compounddef.attrs and compounddef["abstract"] == "yes":
                    __ABSTRACT_CLASSES[thing] = True
            fn_list = xml.find_all("memberdef")
            fn_dict = {}

            for x in fn_list:
                nm = x.find("name").text
                if nm not in fn_dict:
                    fn_dict[nm] = {}
                tparam = x.find("templateparamlist")
                if tparam is not None:
                    tparam = tparam.find_all("param")
                    tparam = [x.find("type").text.strip() for x in tparam]
                param = x.find_all("param")
                param = [x.find("type").text.strip() for x in param]
                if tparam is not None:
                    param = [x for x in param if x not in tparam]
                param = ",".join(param)

                fn_dict[nm][param] = x
            __DOXY_DICT[thing] = fn_dict
    if fn is not None:
        if params_t == "" and len(__DOXY_DICT[thing][fn]) == 1:
            return list(__DOXY_DICT[thing][fn].values())[0]
        if params_t is not None:
            return __DOXY_DICT[thing][fn][params_t]
        return __DOXY_DICT[thing][fn]
    return __DOXY_DICT[thing]


########################################################################
# Query functions (from generate_pybind11.py)
########################################################################


@cache
@accepts(str, str, str)
def is_public(thing: str, fn: str, params_t: str) -> bool:
    if is_namespace(thing):
        return True
    xml = get_xml(thing, fn, params_t)
    prot = xml.get("prot")
    return prot is not None and prot == "public"


# @cache
# @accepts(str, str, str)
# def is_enum(thing: str, fn: str, params_t: str) -> bool:
#     xml = get_xml(thing, fn, params_t)
#     kind = xml.get("kind")
#     return kind is not None and kind == "enum"


@cache
@accepts(str, str, str)
def is_typedef(thing: str, fn: str, params_t: str) -> bool:
    xml = get_xml(thing, fn, params_t)
    kind = xml.get("kind")
    return kind is not None and kind == "typedef"


@cache
@accepts(str)
def class_template_params(thing: str) -> list[str]:
    result = []
    doxy_file = doxygen_filename(thing)
    if is_namespace(thing) or not doxy_file:
        return result
    with open(doxy_file, "r", encoding="utf-8") as xml:
        xml = BeautifulSoup(xml, "xml")
        for x in xml.doxygen.compounddef.children:
            if x.name == "templateparamlist":
                for y in x.find_all("param"):
                    result.append(y.find("type").text)
                    if y.find("declname") is not None:
                        result[-1] += " " + y.find("declname").text
    return result


@cache
@accepts(str)
def is_class_template(thing: str) -> bool:
    return len(class_template_params(thing)) != 0


# @cache
# @accepts(str, str)
# def is_overloaded(thing: str, fn: str) -> bool:
#     return len(get_xml(thing, fn)) > 1


@cache
@accepts(str)
def is_namespace(thing: str) -> bool:
    return "namespace" in doxygen_filename(thing)


# @cache
# @accepts(str)
# def is_free_fn(thing: str) -> bool:
#     return doxygen_filename(thing).startswith(f"{__DOXY_DIR}/group__")


# @cache
# @accepts(str, str, str)
# def is_static_mem_fn(thing: str, fn: str, params_t: str) -> bool:
#     if is_namespace(thing) or is_free_fn(thing):
#         return False
#     xml = get_xml(thing, fn, params_t)
#     return xml["static"] == "yes"


# @cache
# @accepts(str)
# def is_abstract_class(thing: str) -> bool:
#     return thing in __ABSTRACT_CLASSES


@cache
@accepts(str, str, str)
def params_dict(thing: str, fn: str, params_t: str) -> dict[str, str]:
    xml = get_xml(thing, fn, params_t)
    result = {}
    for x in xml.find_all("param"):
        type_ = x.find("type").text
        if not type_.startswith("typename"):
            name = x.find("declname")
            if name:
                result[name.text] = type_
    return result


@cache
@accepts(str, str, str)
def return_type(thing: str, fn: str, params_t: str) -> str:
    xml = get_xml(thing, fn, params_t)
    return xml.find("type").text


# @accepts(str, str, str)
# def param_names_str(thing: str, fn: str, params_t: str) -> list[str]:
#     return list(params_dict(thing, fn, params_t).keys())


# @accepts(str, str, str)
# def fn_sig(thing: str, fn: str, params_t: str) -> list[str]:
#     params_d = params_dict(thing, fn, params_t)
#     result = []
#     for name, type_ in params_d.items():
#         result.append(f"{type_} {name}")
#     return result


@accepts(str)
def shortname(thing: str) -> str:
    if thing.startswith("libsemigroups::"):
        return thing[len("libsemigroups::") :]
    return thing


# @accepts(str)
# def shortname_(thing: str) -> str:
#     name = shortname(thing)
#     if is_class_template(thing):
#         name += "_"
#     return name


# @cache
# @accepts(str, str, str)
# def is_const_mem_fn(thing: str, fn: str, params_t: str) -> bool:
#     if is_namespace(thing):
#         return False
#     xml = get_xml(thing, fn, params_t)
#     assert "const" in xml.attrs, "const not an attribute!"
#     return xml["const"] == "yes"


@cache
@accepts(str, str, str)
def is_deleted_mem_fn(class_n: str, mem_fn: str, params_t: str) -> bool:
    xml = get_xml(class_n, mem_fn, params_t)
    if xml.find("argsstring") is None:
        return False
    return xml.find("argsstring").text.find("=delete") != -1


# @cache
# @accepts(str, str)
# def is_constructor(class_n: str, mem_fn: str) -> bool:
#     return not is_free_fn(class_n) and mem_fn.startswith(class_n.split("::")[-1])


# @cache
# @accepts(str, str)
# def is_operator(_: str, mem_fn: str) -> bool:
#     return mem_fn.startswith("operator") or mem_fn in ("at", "hash_value")


# @cache
# @accepts(str, str)
# def is_iterator(_: str, mem_fn: str) -> bool:
#     # Only use cbegin to avoid duplicate with begin
#     return mem_fn.startswith("cbegin")


@cache
@accepts(str, str, str)
def brief(thing: str, fn: str, params_t: str) -> str:
    xml = get_xml(thing, fn, params_t)
    return xml.find("briefdescription").text.strip()


########################################################################
# Skip logic
########################################################################


@accepts(str, str, str)
def skip_fn(thing: str, fn: str, params_t: str) -> bool:
    if (
        fn.endswith("_no_checks")
        or "initializer_list" in params_t
        or fn.startswith("cend")
        or fn.startswith("end")
        or fn.startswith("begin")
        or fn.startswith("cbegin")
        or fn.startswith("operator")
        or "&&" in params_t
        or ("*" in params_t and params_t.strip() != "bool(*)()")
        or "*" in return_type(thing, fn, params_t)
        or is_typedef(thing, fn, params_t)
        or brief(thing, fn, params_t).startswith("Deduction guide")
    ):
        return True
    try:
        get_xml(thing, fn, params_t)
    except KeyError:
        return True
    return is_deleted_mem_fn(thing, fn, params_t) or not is_public(thing, fn, params_t)


#########################################################################
# Convert to jl
########################################################################


@accepts(str)
def to_jl_type(param_types: str) -> str:
    param_types = param_types.replace("const", "")
    param_types = param_types.replace("&", "")
    param_types = re.sub(param_types, "\bsize_t\b", "Int64")
    param_types = param_types.replace("uint8_t", "Int64")
    param_types = param_types.replace("bool", "Bool")
    param_types = param_types.replace("typename", "")
    param_types = param_types.replace("std::vector", "Vector")
    param_types = param_types.replace("<", "{")
    param_types = param_types.replace(">", "}")
    param_types = param_types.replace(" ", "")

    return param_types


def to_jl_sig(
    thing: str, fn_name: str, param_types: str, include_return_type: bool = False
) -> str:
    result = f"{fn_name}("
    result += ",".join(
        f"{name}::{to_jl_type(type_)}"
        for name, type_ in params_dict(thing, fn_name, param_types).items()
    )
    result += ")"
    if include_return_type:
        result += f"::{to_jl_type(return_type(thing, fn_name, param_types))}"
    return result


def to_jl_ref(thing: str, fn_name: str | None = None, param_types: str | None = None):
    if fn_name is None and param_types is None:
        sig, name = shortname(thing), shortname(thing)
    elif param_types is None:
        sig, name = shortname(fn_name), shortname(fn_name)
    else:
        sig, name = (
            to_jl_sig(thing, fn_name, param_types, include_return_type=False),
            shortname(fn_name),
        )

    return f"[`{name}`](@ref Semigroups.{sig})"


def to_jl_doc(thing: str, text: str) -> str:
    text = re.sub(r"\ba\s+const\s+reference\s+to\s+a\b", "a", text)
    text = re.sub(r"\ba\s+reference\s+to\s+a\b", "a", text)
    text = re.sub(r"\ba\s+const\s+reference\b", "", text)
    text = re.sub(r"\ba\s+reference\b", "", text)
    text = re.sub(r"\bvector\b", "`Vector`", text)
    text = re.sub(r"\buint8_t\b", "`Int64`", text)
    text = re.sub(f"{thing}", to_jl_ref(thing), text)
    return text


########################################################################
# Orchestrator
########################################################################


@accepts(str)
def generate(thing: str) -> str:
    if len(doxygen_filename(thing)) == 0:
        return ""

    result = f"""# The {shortname(thing)} type

This page contains the documentation of the type {to_jl_ref(thing)}.

## Contents

| Function | Description |
| -------- | ----------- |
"""

    xml = get_xml(thing)
    for fn, sigs in sorted(xml.items()):
        for sig in sigs.keys():
            if not skip_fn(thing, fn, sig):
                result += f"| {to_jl_ref(thing, fn, sig)} | {to_jl_doc(thing, brief(thing, fn, sig))} |\n"
    result += """
## Full API

```@docs
"""
    for fn, sigs in sorted(xml.items()):
        for sig in sigs.keys():
            if not skip_fn(thing, fn, sig):
                result += f"Semigroups.{to_jl_sig(thing, fn, sig)}\n"

    result += "```\n"

    return result


########################################################################
# main
########################################################################


def main():
    if sys.version_info[0] < 3:
        raise Exception("Python 3 is required")
    args = __parse_args()

    for thing in args.things:
        print(generate(thing))


if __name__ == "__main__":
    main()
