# Copyright (c) 2026, James W. Swent, J. D. Mitchell
#
# Distributed under the terms of the GPL license version 3.
#
# The full license is in the file LICENSE, distributed with this software.

# This file was at least partially auto-generated by
#
# scripts/doxy_to_jl_file.py --doxy-dir /Users/jdm3/libsemigroups/docs/xml libsemigroups::Forest

"""
forest.jl - High-level Julia API for libsemigroups::Forest

This file provides user-facing libsemigroups::Forest functionality with
idiomatic Julia interfaces: 1-based indexing, and standard Julia operators.
"""

using CxxWrap.StdLib: StdVector

const Forest = LibSemigroups.Forest

const Int64OrUndefined = Union{Int64,UndefinedType}

# TODO add this to the script
function Base.show(io::IO, x::Forest)
    print(io, @wrap_libsemigroups_call LibSemigroups.forest_to_human_readable_repr(x))
end

# TODO add to script
Base.:(==)(x::Forest, y::Forest) = LibSemigroups.forest_is_equal(x, y)
# TODO add to script
Base.:(!=)(x::Forest, y::Forest) = LibSemigroups.forest_is_not_equal(x, y)

"""
    empty(self::Forest)::Bool

Check if there are any nodes in the forest.

This function returns `true` if there are 0 nodes in the forest, and `false`
otherwise.

# Complexity

- Constant
"""
Base.empty(self::Forest)::Bool = LibSemigroups.forest_empty(self)

"""
    Forest(n::Int64)::Forest

Constructs a forest with `n` nodes.

Constructs a forest with `n` nodes, initialised so that the
[`parent_node`](@ref) and [`label`](@ref) of every node are [`UNDEFINED`](@ref).

# Arguments

 - `n::Int64`: the number of nodes (defaults to `0`).
"""
Forest(n::Int64)::Forest = invoke(Forest, Tuple{Integer}, n)

"""
    Forest(parents::Vector{T},labels::Vector{T})::Forest where T

Construct a forest from vectors of parent nodes and edge labels.

The vectors `parents` and `labels` must have the same length. The value in
position `i` determines the parent and edge label for node `i`.
 
# Arguments

 - `parents::Vector{T}`: the parents of the nodes. 
 - `labels::Vector{T}`: the labels of the edges.

 # Throws

- LibsemigroupsError:  if the arguments do not describe a [`Forest`](@ref)
  (e.g. if there are any cycles or loops in `parents`).
- LibsemigroupsError:  if `length(parents)` is not equal to `length(labels)`.
"""
function Forest(parents::Vector{T}, labels::Vector{T}) where T
    return @wrap_libsemigroups_call LibSemigroups.forest_make(
        StdVector{UInt32}(convert.(UInt32, parents.-1)),
        StdVector{UInt32}(convert.(UInt32, labels.-1)),
    )
end

"""
    add_nodes!(self::Forest,n::Int64)::Forest

Add nodes to the [`Forest`](@ref).

This function adds `n` nodes to the forest, but no edges.

# Arguments

 - `n::Int64`: the number of nodes to add.

# Complexity

- At most linear in `number_of_nodes() + n`.
"""
add_nodes!(self::Forest, n::Int64)::Forest = LibSemigroups.forest_add_nodes(self, n)[]


"""
    init!(self::Forest,n::Int64)::Forest

Reinitialize an existing [`Forest`](@ref) object.

This function reinitializes an existing [`Forest`](@ref) object so that it is in
the same state as if it had just been constructed as `Forest(n)`.

# Arguments

 - `n::Int64`: the number of nodes, defaults to 0.
"""
init!(self::Forest, n::Int64)::Forest = LibSemigroups.forest_init(self, n)[]

# TODO doc
init!(self::Forest)::Forest = init!(self, 0)

"""
    label(self::Forest,i::Int64)::Int64OrUndefined

Returns the label of the edge from a node to its parent.

This function returns the label of the edge from the parent of `i` to the node
`i`. The value [`UNDEFINED`](@ref) is returned if `i` has no parent, i.e. when
`i` is a root node.

# Arguments

 - `i::Int64`: the node whose label is sought.

 # Throws

- LibsemigroupsError:  if `i` exceeds `number_of_nodes(self)`.

# Complexity

- Constant
"""
label(self::Forest, i::Int64OrUndefined)::Int64OrUndefined =
    @wrap_libsemigroups_call convert(
        Int64OrUndefined,
        LibSemigroups.forest_label(self, i - 1),
    ) + 1

"""
    labels(self::Forest)::Vector{Int64OrUndefined}

Returns the `Vector` of edge labels.

This function returns the `Vector` of edge labels in the [`Forest`](@ref).
The value in position `i` of this `Vector` is the label of the edge from the
parent of node `i` to `i`. If the parent equals [`UNDEFINED`](@ref), then node
`i` is a root node.

# Complexity

- Constant.
"""
labels(self::Forest)::Vector{Int64OrUndefined} =
    convert(Vector{Int64OrUndefined}, LibSemigroups.forest_labels(self)[]) .+ 1

"""
    number_of_nodes(self::Forest)::Int64

Returns the number of nodes in the forest.

This function returns the number of nodes in the forest.

# Complexity

- Constant
"""
number_of_nodes(self::Forest)::Int64 = LibSemigroups.forest_number_of_nodes(self)

"""
    parent_node(self::Forest,i::Int64)::Int64OrUndefined

Returns the parent of a node.

This function returns the parent of the node `i` in the forest. The value
[`UNDEFINED`](@ref) is returned if `i` has no parent, i.e. when `i` is a root
node.

# Arguments

 - `i::Int64`: the node whose parent is sought.

 # Throws

- LibsemigroupsError:  if `i` exceeds `number_of_nodes(self)`. 

# Complexity

- Constant
"""
function parent_node(self::Forest, i::Int64)::Int64OrUndefined
    return @wrap_libsemigroups_call convert(
        Int64OrUndefined,
        LibSemigroups.forest_parent(self, i - 1),
    ) + 1
end

"""
    parents(self::Forest)::Vector{Int64OrUndefined}

Returns the `Vector` of parents.

This function returns the `Vector` of parents in the [`Forest`](@ref). The
value in position `i` of this `Vector` is the parent of node `i`. If the parent
equals [`UNDEFINED`](@ref), then node `i` is a root node.

# Complexity

- Constant.
"""
parents(self::Forest)::Vector{Int64OrUndefined} =
    convert(Vector{Int64OrUndefined}, LibSemigroups.forest_parents(self)[]) .+ 1

"""
    set_parent_and_label!(self::Forest,node::Int64,parent::Int64OrUndefined,gen::Int64OrUndefined)::Forest

Set the parent and edge label for a node.

This function sets the parent of `node` to be `parent`, and the associated
edge-label to be `gen`.

# Arguments

 - `node::Int64`: the node whose parent and label to set.
 - `parent::Int64OrUndefined`: the parent node.
 - `gen::Int64OrUndefined`: the label of the edge from parent to node.

 # Throws

- LibsemigroupsError:  if `node` or `parent` exceeds [`number_of_nodes`](@ref).
- LibsemigroupsError:  if `node` equals `parent`.
- LibsemigroupsError:  if adding `parent` as the parent of `node` would result
    in a cycle.

# Complexity

- Constant
"""
set_parent_and_label!(
    self::Forest,
    node::Int64,
    parent::Int64OrUndefined,
    gen::Int64OrUndefined,
)::Forest = @wrap_libsemigroups_call LibSemigroups.forest_set_parent_and_label(
    self,
    node - 1,
    parent - 1,
    gen - 1,
)[]
