# Copyright (c) 2026, James W. Swent, J. D. Mitchell
#
# Distributed under the terms of the GPL license version 3.
#
# The full license is in the file LICENSE, distributed with this software.

# This file was at least partially auto-generated by
#
# scripts/doxy_to_jl_file.py --doxy-dir /Users/jdm3/libsemigroups/docs/xml libsemigroups::Forest

"""
forest.jl - High-level Julia API for libsemigroups::Forest

This file provides user-facing libsemigroups::Forest functionality with
idiomatic Julia interfaces: 1-based indexing, and standard Julia operators.
"""

using CxxWrap.StdLib: StdVector

const Forest = LibSemigroups.Forest

# TODO add this to the script
function Base.show(io::IO, x::Forest)
    print(io, @wrap_libsemigroups_call LibSemigroups.forest_to_human_readable_repr(x))
end

"""
    empty(self::Forest)::Bool

Check if there are any nodes in the forest.

This function returns `true` if there are 0 nodes in the forest, and `false`
otherwise.

# Complexity

Constant
"""
Base.empty(self::Forest)::Bool = LibSemigroups.forest_empty(self)

"""
    Forest()::Forest

Default copy constructor.
"""

"""
    Forest(n::Int64)::Forest

Constructs a forest with `n` nodes.

Constructs a forest with `n` nodes, that is initialised so that the
[`parent`](@ref) and [`label`](@ref) of every node is UNDEFINED.

# Arguments

 - `n::Int64`: the number of nodes, defaults to 0.
"""

function Forest(parents::Vector{Any}, labels::Vector{Any})
    parents = [x == UNDEFINED ? x : UInt32(x - 1) for x in parents] 
    labels = [x == UNDEFINED ? x : UInt32(x - 1) for x in labels] 
    return @wrap_libsemigroups_call LibSemigroups.forest_make(StdVector{UInt32}(parents), StdVector{UInt32}(labels))
end

"""
    add_nodes!(self::Forest,n::Int64)::Forest

Add nodes to the [`Forest`](@ref).

This function adds `n` nodes to the forest, but no edges.

# Arguments

 - `n::Int64`: the number of nodes to add.

 exception is thrown, `self` is guaranteed not to be modified (strong exception
guarantee).

# Complexity

At most linear in `number_of_nodes() + n`.
"""
add_nodes!(self::Forest, n::Int64)::Forest = LibSemigroups.forest_add_nodes(self, n)[]


"""
    init!(self::Forest,n::Int64)::Forest

Reinitialize an existing [`Forest`](@ref) object.

This function reinitializes an existing [`Forest`](@ref) object so that it is in
the same state as if it had just be constructed as `Forest(n)`.

# Arguments

 - `n::Int64`: the number of nodes, defaults to 0.
"""
init!(self::Forest, n::Int64)::Forest = LibSemigroups.forest_init(self, n)[]

# TODO doc
init!(self::Forest)::Forest = init!(self, 0)

"""
    label(self::Forest,i::Integer)::Integer

Returns the label of the edge from a node to its parent.

This function returns the label of the edge from the parent of `i` to the node
`i`. The value [`UNDEFINED`](@ref) is returned if `i` has no parent, i.e. when
`i` is a root node.

# Arguments

 - `i::Integer`: the node whose label is sought.

 # Throws

- LibsemigroupsError:  if `i` exceeds `number_of_nodes()`.

# Complexity

Constant
"""
label(self::Forest, i::Integer)::Integer =
    @wrap_libsemigroups_call LibSemigroups.forest_label(self, i) + 1

"""
    labels(self::Forest)::Vector{Integer}

Returns  to the `Vector` of edge labels.

This function returns  to the `Vector` of edge labels in the [`Forest`](@ref).
The value in position `i` of this `Vector` is the label of the edge from the
parent of node `i` to `i`. If the parent equals UNDEFINED, then node `i` is a
root node.

# Complexity

Constant.
"""
labels(self::Forest)::Vector{Integer} = LibSemigroups.forest_labels(self)[]

"""
    number_of_nodes(self::Forest)::Int64

Returns the number of nodes in the forest.

This function returns the number of nodes in the forest.

# Complexity

Constant
"""
number_of_nodes(self::Forest)::Int64 = LibSemigroups.forest_number_of_nodes(self)

"""
    parent(self::Forest,i::Integer)::Integer

Returns the parent of a node.

This function returns the parent of the node `i` in the forest. The value
[`UNDEFINED`](@ref) is returned if `i` has no parent, i.e. when `i` is a root
node.

# Arguments

 - `i::Integer`: the node whose parent is sought.

 # Throws

- LibsemigroupsError:  if `i` exceeds `number_of_nodes()`. 

# Complexity

Constant
"""
function parent_node(self::Forest, i::Integer)::Union{Integer,UndefinedType}
    @wrap_libsemigroups_call to_undefined(
        LibSemigroups.forest_parent(self, i - 1),
    ) + 1
end

"""
    parents(self::Forest)::Vector{Integer}

Returns  to the `Vector` of parents.

This function returns  to the `Vector` of parents in the [`Forest`](@ref). The
value in position `i` of this `Vector` is the parent of node `i`. If the parent
equals UNDEFINED, then node `i` is a root node.

# Complexity

Constant.
"""
function parents(self::Forest)::Vector{Any}
  return [x == typemax(UInt32) ? UNDEFINED : Integer(x + 1) for x in LibSemigroups.forest_parents(self)[]] 
end

"""
    path_from_root(self::Forest,d_first::Iterator,i::Integer)::Iterator

template <typename Iterator>Store the labels of the edges on the path from a root node to a given node.

This function writes labels of the edges on the path from a root node to node
`i` to the iterator `d_first`.

# Arguments

 - `d_first::Iterator`: the output iterator.

 - `i::Integer`: the node.

 # Throws

- LibsemigroupsError:  if `i` is greater than or equal to
[`number_of_nodes`](@ref).

- LibsemigroupsError:  if `self` is not acyclic.

# See also

- [`forest::PathsFromRoots`](@ref)
"""
# path_from_root(self::Forest, d_first::Iterator, i::Integer)::Iterator =
#    @wrap_libsemigroups_call LibSemigroups.forest_path_from_root(self, d_first, i)

"""
    path_to_root(self::Forest,d_first::Iterator,i::Integer)::Iterator

template <typename Iterator>Store the labels of the edges on the path to a root node from a given node.

This function writes labels of the edges on the path to a root node from node
`i` to the iterator `d_first`.

# Arguments

 - `d_first::Iterator`: the output iterator.

 - `i::Integer`: the node.

 # Throws

- LibsemigroupsError:  if `i` is greater than or equal to
[`number_of_nodes`](@ref).

- LibsemigroupsError:  if `self` is not acyclic.
"""
# path_to_root(self::Forest, d_first::Iterator, i::Integer)::Iterator =
#     @wrap_libsemigroups_call LibSemigroups.forest_path_to_root(self, d_first, i)

"""
    set_parent_and_label!(self::Forest,node::Integer,parent::Integer,gen::Integer)::Forest

Set the parent and edge label for a node.

This function sets the parent of `node` to be `parent`, and the associated
edge-label to be `gen`.

# Arguments

 - `node::Integer`: the node whose parent and label to set.

 - `parent::Integer`: the parent node.

 - `gen::Integer`: the label of the edge from parent to node.

 # Throws

- LibsemigroupsError:  if `node` or `parent` exceeds [`number_of_nodes`](@ref).

- LibsemigroupsError:  if `node` equals `parent`.

- LibsemigroupsError:  if adding `parent` as the parent of `node` would result
in a cycle.

# Complexity

Constant
"""
set_parent_and_label!(self::Forest, node::Integer, parent::Integer, gen::Integer)::Forest =
    @wrap_libsemigroups_call LibSemigroups.forest_set_parent_and_label(
        self,
        node,
        parent,
        gen,
    )[]
