name: Run tests
on: [pull_request, workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# needed to allow julia-actions/cache to delete old caches that it has created
permissions:
  actions: write
  contents: read

jobs:
  test:
    name: "${{ matrix.system.os }}: Version ${{ matrix.julia-version }}"
    runs-on: ${{ matrix.system.os }}
    strategy:
      fail-fast: false
      matrix:
        julia-version: ["1.10", "lts", "1", "pre"]
        system:
          # TODO: test with x86
          - {
              os: ubuntu-latest,
              arch: default,
              coverage: true,
            }
          - {
              os: macOS-latest,
              arch: default,
              coverage: false,
            }
          - {
              os: macOS-15-intel,
              arch: default,
              coverage: false,
            }

    steps:
      - uses: actions/checkout@v7

        # Setup Julia
      - uses: julia-actions/setup-julia@v3
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.system.arch }}
      - uses: julia-actions/cache@v3

        # Build Semigroups.jl
      - uses: julia-actions/julia-buildpkg@v1
        with:
          precompile: yes

      - name: Check registered JLL binaries
        run: julia --startup-file=no --project=. test/check_jll.jl

      # Run the tests
      - uses: julia-actions/julia-runtest@v1

      # Upload coverage
      - uses: julia-actions/julia-processcoverage@v1
        if: ${{ matrix.system.coverage && matrix.julia-version == '1' }}
      - uses: codecov/codecov-action@v7
        if: ${{ matrix.system.coverage && matrix.julia-version == '1' }}
        with:
          files: lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
